// @generated — DO NOT EDIT BY HAND.
// Generated by scripts/gen-tax-snapshot.ts using the hmrc-tax-mcp rule set.
// Run `npm run gen:tax-snapshot` inside the Copilot CLI environment to refresh.
//
// Rule coverage is intentionally uneven:
//   income_tax_bands  → confirmed 2025-26 through 2030-31
//   cgt_due           → confirmed 2025-26 and 2026-27 only
//   pension_lsa / UFPLS → confirmed 2025-26 and 2026-27 only
//   state_pension_annual → confirmed 2025-26 and 2026-27 only
//
// For simulation years beyond the confirmed range, getSnapshotForYear falls
// back to the latest available entry and emits a console.warn (suppressed
// in test environments).
//
// HMRC citations:
//   income_tax_bands: https://www.gov.uk/income-tax-rates ; ITA 2007 s.35
//   cgt_due:          https://www.gov.uk/capital-gains-tax/allowances ; Autumn Budget 2024
//   pension_lsa:      https://www.gov.uk/government/publications/rates-and-allowances-pension-schemes ; Finance Act 2024 s.18
//   state_pension:    https://www.gov.uk/new-state-pension

// ─── Interfaces ──────────────────────────────────────────────────────────────

export interface IncomeTaxBands {
  taxYear: string;
  jurisdiction: 'rUK';
  ruleId: 'income_tax_bands';
  ruleVersion: string;
  personalAllowance: number;
  basicRateLimit: number;         // top of basic-rate band (e.g. £50,270)
  additionalRateThreshold: number; // above this rate is 45% (£125,140)
  paTaperThreshold: number;       // PA taper starts at £100,000
  basicRate: number;              // 0.20
  higherRate: number;             // 0.40
  additionalRate: number;         // 0.45
}

export interface CgtSnapshot {
  taxYear: string;
  jurisdiction: 'rUK';
  ruleId: 'cgt_due';
  ruleVersion: string;
  exemptAmount: number;           // £3,000
  basicRate: number;              // 0.18 (non-property assets, post Autumn Budget 2024)
  higherRate: number;             // 0.24 (non-property assets, post Autumn Budget 2024)
}

export interface PensionSnapshot {
  taxYear: string;
  jurisdiction: 'rUK';
  lsa: number;                    // Lifetime Lump Sum Allowance (£268,275)
  ufplsTaxFreeFraction: number;   // 0.25 — tax-free portion of each UFPLS withdrawal
  ufplsTaxableFraction: number;   // 0.75 — taxable portion of each UFPLS withdrawal
}

export interface StatePensionSnapshot {
  taxYear: string;
  jurisdiction: 'rUK';
  ruleVersion: string;
  annualAmount: number;           // Full new State Pension annual amount (£)
}

// ─── Sentinel constants ───────────────────────────────────────────────────────
// The latest confirmed tax year for each rule group. Snapshot entries exist up
// to and including these years. The generator must be re-run when HMRC publishes
// new rates beyond these years.

export const LATEST_INCOME_TAX_YEAR = '2030-31';
export const LATEST_CGT_YEAR        = '2026-27';
export const LATEST_PENSION_YEAR    = '2026-27';
export const LATEST_STATE_PENSION_YEAR = '2026-27';

// ─── Snapshot data ────────────────────────────────────────────────────────────
// Stored per rule group, each keyed by UK tax year (e.g. '2025-26').

const incomeTaxBandsData: Record<string, IncomeTaxBands> = {
  '2025-26': {
    taxYear: '2025-26', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.1',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2026-27': {
    taxYear: '2026-27', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2027-28': {
    taxYear: '2027-28', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2028-29': {
    taxYear: '2028-29', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2029-30': {
    taxYear: '2029-30', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2030-31': {
    taxYear: '2030-31', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
};

// CGT: only confirmed for 2025-26 and 2026-27.
// HMRC has not published CGT rates beyond 2026-27.
const cgtData: Record<string, CgtSnapshot> = {
  '2025-26': {
    taxYear: '2025-26', jurisdiction: 'rUK' as const, ruleId: 'cgt_due' as const, ruleVersion: '1.0.0',
    exemptAmount: 3_000,
    basicRate: 0.18,
    higherRate: 0.24,
  },
  '2026-27': {
    taxYear: '2026-27', jurisdiction: 'rUK' as const, ruleId: 'cgt_due' as const, ruleVersion: '1.0.0',
    exemptAmount: 3_000,
    basicRate: 0.18,
    higherRate: 0.24,
  },
};

// Pension: only confirmed for 2025-26 and 2026-27.
const pensionData: Record<string, PensionSnapshot> = {
  '2025-26': {
    taxYear: '2025-26', jurisdiction: 'rUK' as const,
    lsa: 268_275,
    ufplsTaxFreeFraction: 0.25,
    ufplsTaxableFraction: 0.75,
  },
  '2026-27': {
    taxYear: '2026-27', jurisdiction: 'rUK' as const,
    lsa: 268_275,
    ufplsTaxFreeFraction: 0.25,
    ufplsTaxableFraction: 0.75,
  },
};

// State pension annual amounts.
const statePensionData: Record<string, StatePensionSnapshot> = {
  '2025-26': { taxYear: '2025-26', jurisdiction: 'rUK' as const, ruleVersion: '1.1.0', annualAmount: 11502.4 },
  '2026-27': { taxYear: '2026-27', jurisdiction: 'rUK' as const, ruleVersion: '1.0.0', annualAmount: 11973 }, // estimated; update to confirmed DWP figure when published
};

export const TAX_RULE_SNAPSHOT = {
  incomeTaxBands: incomeTaxBandsData,
  cgt: cgtData,
  pension: pensionData,
  statePension: statePensionData,
};

// ─── Resolved snapshot returned by getSnapshotForYear ────────────────────────

export interface ResolvedSnapshot {
  taxYear: string;
  incomeTaxBands: IncomeTaxBands;
  cgt: CgtSnapshot;
  pension: PensionSnapshot;
  statePensionAnnual: number;
  /** true if cgt entry for the requested year was absent; 2026-27 rates used instead. */
  cgtFallback: boolean;
  /** true if pension entry for the requested year was absent; 2026-27 rates used instead. */
  pensionFallback: boolean;
}

/**
 * Look up the tax rule snapshot for a given calendar year.
 *
 * Maps calendarYear to a UK tax year: `${calendarYear}-${(calendarYear+1) % 100}`.
 *
 * Rule coverage is not uniform:
 *  - Income tax bands: confirmed through 2030-31 (falls back to 2030-31 entry if beyond).
 *  - CGT / pension: confirmed through 2026-27 only. Falls back and sets cgtFallback /
 *    pensionFallback flags. A console.warn is emitted per group (suppressed in NODE_ENV=test).
 *
 * @param calendarYear - e.g. 2025 maps to tax year "2025-26"
 */
export function getSnapshotForYear(calendarYear: number): ResolvedSnapshot {
  const taxYear = `${calendarYear}-${String(calendarYear + 1).slice(-2)}`;

  // Income tax: full coverage through 2030-31.
  const incomeTaxBands =
    TAX_RULE_SNAPSHOT.incomeTaxBands[taxYear] ??
    TAX_RULE_SNAPSHOT.incomeTaxBands[LATEST_INCOME_TAX_YEAR];

  // CGT: only confirmed to 2026-27. Fall back gracefully.
  const cgtEntry = TAX_RULE_SNAPSHOT.cgt[taxYear];
  const cgtFallback = !cgtEntry;
  const cgt = cgtEntry ?? TAX_RULE_SNAPSHOT.cgt[LATEST_CGT_YEAR];

  // Pension: only confirmed to 2026-27. Fall back gracefully.
  const pensionEntry = TAX_RULE_SNAPSHOT.pension[taxYear];
  const pensionFallback = !pensionEntry;
  const pension = pensionEntry ?? TAX_RULE_SNAPSHOT.pension[LATEST_PENSION_YEAR];

  // State pension: only confirmed to 2026-27. Fall back gracefully.
  const spEntry = TAX_RULE_SNAPSHOT.statePension[taxYear];
  const statePensionAnnual = spEntry
    ? spEntry.annualAmount
    : TAX_RULE_SNAPSHOT.statePension[LATEST_STATE_PENSION_YEAR].annualAmount;

  if (process.env.NODE_ENV !== 'test') {
    if (cgtFallback) {
      console.warn(
        `[hmrc-tax-mcp] CGT rules not confirmed for ${taxYear}. ` +
        `Using latest available entry (2026-27). ` +
        `Update snapshot when HMRC publishes new CGT rates.`,
      );
    }
    if (pensionFallback) {
      console.warn(
        `[hmrc-tax-mcp] Pension rules not confirmed for ${taxYear}. ` +
        `Using latest available entry (2026-27). ` +
        `Update snapshot when HMRC publishes new pension allowances.`,
      );
    }
    if (!spEntry) {
      console.warn(
        `[hmrc-tax-mcp] State pension annual amount not confirmed for ${taxYear}. ` +
        `Using latest available entry (2026-27).`,
      );
    }
  }

  return { taxYear, incomeTaxBands, cgt, pension, statePensionAnnual, cgtFallback, pensionFallback };
}
