// @generated — DO NOT EDIT BY HAND.
// Generated by scripts/gen-tax-snapshot.ts using the hmrc-tax-mcp rule set.
// Run `npm run gen:tax-snapshot` inside the Copilot CLI environment to refresh.
//
// Rule coverage is intentionally uneven:
//   income_tax_bands  → confirmed 2025-26 through 2030-31 (frozen at 2025/26 values
//                        per Autumn Budget 2025; escalated at 4%/yr beyond 2030-31)
//   cgt_due           → confirmed 2025-26 and 2026-27 only
//   pension_lsa / UFPLS → confirmed 2025-26 and 2026-27 only
//   state_pension_annual → confirmed 2025-26 and 2026-27 only
//
// For simulation years beyond the confirmed range, getSnapshotForYear falls
// back to the latest available entry. Income-tax thresholds (not rates) are
// then escalated post-freeze at TAX_BAND_ESCALATION_RATE (4%/yr, matching
// the Voyant Default Tax Table Assumption). To avoid console noise during long
// projections, a console.warn is emitted at most once per rule group per
// process (suppressed in test environments).
//
// HMRC citations:
//   income_tax_bands: https://www.gov.uk/income-tax-rates ; ITA 2007 s.35
//   cgt_due:          https://www.gov.uk/capital-gains-tax/allowances ; Autumn Budget 2024
//   pension_lsa:      https://www.gov.uk/government/publications/rates-and-allowances-pension-schemes ; Finance Act 2024 s.18
//   state_pension:    https://www.gov.uk/new-state-pension

// ─── Interfaces ──────────────────────────────────────────────────────────────

export interface IncomeTaxBands {
  taxYear: string;
  jurisdiction: 'rUK';
  ruleId: 'income_tax_bands';
  ruleVersion: string;
  personalAllowance: number;
  basicRateLimit: number;         // top of basic-rate band (e.g. £50,270)
  additionalRateThreshold: number; // above this rate is 45% (£125,140)
  paTaperThreshold: number;       // PA taper starts at £100,000
  basicRate: number;              // 0.20
  higherRate: number;             // 0.40
  additionalRate: number;         // 0.45
}

export interface CgtSnapshot {
  taxYear: string;
  jurisdiction: 'rUK';
  ruleId: 'cgt_due';
  ruleVersion: string;
  exemptAmount: number;           // £3,000
  basicRate: number;              // 0.18 (non-property assets, post Autumn Budget 2024)
  higherRate: number;             // 0.24 (non-property assets, post Autumn Budget 2024)
}

export interface PensionSnapshot {
  taxYear: string;
  jurisdiction: 'rUK';
  lsa: number;                    // Lifetime Lump Sum Allowance (£268,275)
  ufplsTaxFreeFraction: number;   // 0.25 — tax-free portion of each UFPLS withdrawal
  ufplsTaxableFraction: number;   // 0.75 — taxable portion of each UFPLS withdrawal
}

export interface StatePensionSnapshot {
  taxYear: string;
  jurisdiction: 'rUK';
  ruleVersion: string;
  annualAmount: number;           // Full new State Pension annual amount (£)
}

// ─── Sentinel constants ───────────────────────────────────────────────────────
// The latest confirmed tax year for each rule group. Snapshot entries exist up
// to and including these years. The generator must be re-run when HMRC publishes
// new rates beyond these years.

export const LATEST_INCOME_TAX_YEAR = '2030-31';
export const LATEST_CGT_YEAR        = '2026-27';
export const LATEST_PENSION_YEAR    = '2026-27';
export const LATEST_STATE_PENSION_YEAR = '2026-27';

// ─── Post-freeze band escalation ─────────────────────────────────────────────
// UK income-tax thresholds (PA, basic-rate limit, additional-rate threshold,
// PA-taper threshold) are legislatively frozen until 5 April 2031.
// Source: Autumn Budget 2025 — HM Treasury, October 2025.
//
// For simulation years beyond the freeze, the software escalates these
// thresholds at TAX_BAND_ESCALATION_RATE per year, matching the approach used
// by Voyant (Default Tax Table Assumption = 4%).
//
// TAX_BAND_FREEZE_END_YEAR is the last calendar year in which bands remain
// frozen (i.e. tax year 2030-31). Escalation begins from calendar year 2031
// (tax year 2031-32) onward.
//
// To change the escalation rate, update TAX_BAND_ESCALATION_RATE here.
// Note: tax *rates* (20%, 40%, 45%) are never escalated — only the thresholds.
export const TAX_BAND_FREEZE_END_YEAR   = 2030; // last frozen calendar year (tax year 2030-31)
export const TAX_BAND_ESCALATION_RATE   = 0.04; // 4%/yr post-freeze (matches Voyant default)

// ─── Snapshot data ────────────────────────────────────────────────────────────
// Stored per rule group, each keyed by UK tax year (e.g. '2025-26').

const incomeTaxBandsData: Record<string, IncomeTaxBands> = {
  '2025-26': {
    taxYear: '2025-26', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.1',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2026-27': {
    taxYear: '2026-27', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2027-28': {
    taxYear: '2027-28', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2028-29': {
    taxYear: '2028-29', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2029-30': {
    taxYear: '2029-30', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
  '2030-31': {
    taxYear: '2030-31', jurisdiction: 'rUK' as const, ruleId: 'income_tax_bands' as const,
    ruleVersion: '1.0.0',
    personalAllowance: 12_570,
    basicRateLimit: 50_270,
    additionalRateThreshold: 125_140,
    paTaperThreshold: 100_000,
    basicRate: 0.2,
    higherRate: 0.4,
    additionalRate: 0.45,
  },
};

// CGT: only confirmed for 2025-26 and 2026-27.
// HMRC has not published CGT rates beyond 2026-27.
const cgtData: Record<string, CgtSnapshot> = {
  '2025-26': {
    taxYear: '2025-26', jurisdiction: 'rUK' as const, ruleId: 'cgt_due' as const, ruleVersion: '1.0.0',
    exemptAmount: 3_000,
    basicRate: 0.18,
    higherRate: 0.24,
  },
  '2026-27': {
    taxYear: '2026-27', jurisdiction: 'rUK' as const, ruleId: 'cgt_due' as const, ruleVersion: '1.0.0',
    exemptAmount: 3_000,
    basicRate: 0.18,
    higherRate: 0.24,
  },
};

// Pension: only confirmed for 2025-26 and 2026-27.
const pensionData: Record<string, PensionSnapshot> = {
  '2025-26': {
    taxYear: '2025-26', jurisdiction: 'rUK' as const,
    lsa: 268_275,
    ufplsTaxFreeFraction: 0.25,
    ufplsTaxableFraction: 0.75,
  },
  '2026-27': {
    taxYear: '2026-27', jurisdiction: 'rUK' as const,
    lsa: 268_275,
    ufplsTaxFreeFraction: 0.25,
    ufplsTaxableFraction: 0.75,
  },
};

// State pension annual amounts.
const statePensionData: Record<string, StatePensionSnapshot> = {
  '2025-26': { taxYear: '2025-26', jurisdiction: 'rUK' as const, ruleVersion: '1.1.0', annualAmount: 11502.4 },
  '2026-27': { taxYear: '2026-27', jurisdiction: 'rUK' as const, ruleVersion: '1.0.0', annualAmount: 11973 }, // estimated; update to confirmed DWP figure when published
};

export const TAX_RULE_SNAPSHOT = {
  incomeTaxBands: incomeTaxBandsData,
  cgt: cgtData,
  pension: pensionData,
  statePension: statePensionData,
};

// ─── Resolved snapshot returned by getSnapshotForYear ────────────────────────

export interface ResolvedSnapshot {
  taxYear: string;
  incomeTaxBands: IncomeTaxBands;
  cgt: CgtSnapshot;
  pension: PensionSnapshot;
  statePensionAnnual: number;
  /** true if cgt entry for the requested year was absent; 2026-27 rates used instead. */
  cgtFallback: boolean;
  /** true if pension entry for the requested year was absent; 2026-27 rates used instead. */
  pensionFallback: boolean;
}

/** Memoized resolved snapshots keyed by calendarYear to avoid repeated lookups and log spam. */
const _resolvedCache = new Map<number, ResolvedSnapshot>();
/** Tracks which rule-group fallback warnings have already been emitted this process. */
const _warnedKeys = new Set<string>();

/**
 * Look up the tax rule snapshot for a given calendar year.
 *
 * Maps calendarYear to a UK tax year: `${calendarYear}-${(calendarYear+1) % 100}`.
 *
 * Rule coverage is not uniform:
 *  - Income tax bands: confirmed through 2030-31 (frozen at 2025/26 values per Finance Act).
 *    For years beyond 2030, thresholds are escalated at TAX_BAND_ESCALATION_RATE (4%/yr)
 *    from the 2030-31 frozen baseline — matching Voyant's Default Tax Table Assumption.
 *    Tax *rates* (20%, 40%, 45%) are never escalated, only the monetary thresholds.
 *  - CGT / pension / state pension: confirmed only through their latest published years.
 *    Fallback flags still indicate missing-year use, but console warnings are emitted
 *    at most once per rule group per process to avoid projection log spam
 *    (suppressed entirely in NODE_ENV=test).
 *
 * @param calendarYear - e.g. 2025 maps to tax year "2025-26"
 */
export function getSnapshotForYear(calendarYear: number): ResolvedSnapshot {
  const cached = _resolvedCache.get(calendarYear);
  if (cached) return cached;

  const taxYear = `${calendarYear}-${String(calendarYear + 1).slice(-2)}`;

  // Income tax: confirmed through 2030-31 (all frozen at 2025/26 values).
  // Beyond the freeze, escalate monetary thresholds at TAX_BAND_ESCALATION_RATE per year.
  // Tax rates (basicRate, higherRate, additionalRate) are never escalated.
  let incomeTaxBands =
    TAX_RULE_SNAPSHOT.incomeTaxBands[taxYear] ??
    TAX_RULE_SNAPSHOT.incomeTaxBands[LATEST_INCOME_TAX_YEAR];

  if (calendarYear > TAX_BAND_FREEZE_END_YEAR) {
    const yearsPostFreeze = calendarYear - TAX_BAND_FREEZE_END_YEAR;
    const factor = Math.pow(1 + TAX_BAND_ESCALATION_RATE, yearsPostFreeze);
    const frozen = TAX_RULE_SNAPSHOT.incomeTaxBands[LATEST_INCOME_TAX_YEAR];
    incomeTaxBands = {
      ...frozen,
      taxYear,
      personalAllowance:        Math.round(frozen.personalAllowance        * factor),
      basicRateLimit:           Math.round(frozen.basicRateLimit           * factor),
      additionalRateThreshold:  Math.round(frozen.additionalRateThreshold  * factor),
      paTaperThreshold:         Math.round(frozen.paTaperThreshold         * factor),
      // basicRate / higherRate / additionalRate intentionally not escalated
    };
  }

  // CGT: only confirmed to 2026-27. Fall back gracefully.
  const cgtEntry = TAX_RULE_SNAPSHOT.cgt[taxYear];
  const cgtFallback = !cgtEntry;
  const cgt = cgtEntry ?? TAX_RULE_SNAPSHOT.cgt[LATEST_CGT_YEAR];

  // Pension: only confirmed to 2026-27. Fall back gracefully.
  const pensionEntry = TAX_RULE_SNAPSHOT.pension[taxYear];
  const pensionFallback = !pensionEntry;
  const pension = pensionEntry ?? TAX_RULE_SNAPSHOT.pension[LATEST_PENSION_YEAR];

  // State pension: only confirmed to 2026-27. Fall back gracefully.
  const spEntry = TAX_RULE_SNAPSHOT.statePension[taxYear];
  const statePensionAnnual = spEntry
    ? spEntry.annualAmount
    : TAX_RULE_SNAPSHOT.statePension[LATEST_STATE_PENSION_YEAR].annualAmount;

  if (process.env.NODE_ENV !== 'test') {
    const warn = (key: string, message: string) => {
      if (!_warnedKeys.has(key)) {
        _warnedKeys.add(key);
        console.warn(message);
      }
    };
    if (cgtFallback) {
      warn(
        'cgt',
        `[hmrc-tax-mcp] CGT rules not confirmed for ${taxYear}. ` +
        `Using latest available entry (2026-27). ` +
        `Update snapshot when HMRC publishes new CGT rates.`,
      );
    }
    if (pensionFallback) {
      warn(
        'pension',
        `[hmrc-tax-mcp] Pension rules not confirmed for ${taxYear}. ` +
        `Using latest available entry (2026-27). ` +
        `Update snapshot when HMRC publishes new pension allowances.`,
      );
    }
    if (!spEntry) {
      warn(
        'state-pension',
        `[hmrc-tax-mcp] State pension annual amount not confirmed for ${taxYear}. ` +
        `Using latest available entry (2026-27).`,
      );
    }
  }

  const resolved: ResolvedSnapshot = {
    taxYear, incomeTaxBands, cgt, pension, statePensionAnnual, cgtFallback, pensionFallback,
  };
  _resolvedCache.set(calendarYear, resolved);
  return resolved;
}
